# Site settings
title: /dav/null
email: dvalts@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Some musings about life, code, and biscuits. Mainly code.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://decvalts.github.io" # the base hostname & protocol for your site
twitter_username: dvalts
github_username:  decvalts

# Build settings
markdown: kramdown
highlighter: rouge
